# Generated by Django 4.2.21 on 2025-05-31 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='Номерной знак')),
                ('driver_name', models.CharField(max_length=100, verbose_name='Имя водителя')),
                ('status', models.CharField(choices=[('AWAITING_ARRIVAL', 'Ожидает прибытия'), ('READY_TO_ENTER', 'Готов к заезду'), ('ON_TERRITORY', 'Заехал на территорию'), ('LOADING', 'В процессе погрузки'), ('LOADED', 'Погружен'), ('DEPARTED', 'Выехал в рейс')], default='AWAITING_ARRIVAL', max_length=20, verbose_name='Статус')),
                ('arrival_time', models.DateTimeField(blank=True, null=True, verbose_name='Время прибытия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Транспорт',
                'verbose_name_plural': 'Транспорт',
            },
        ),
    ]
