# Generated by Django 4.2.21 on 2025-06-01 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('truck_tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='created_at',
        ),
        migrations.AddField(
            model_name='truck',
            name='doc_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата документа'),
        ),
        migrations.AddField(
            model_name='truck',
            name='doc_guid',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True, verbose_name='Идентификатор документа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='truck',
            name='gate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Ворота'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='license_plate',
            field=models.CharField(max_length=20, verbose_name='Номерной знак'),
        ),
    ]
