# Generated by Django 4.2.21 on 2025-06-03 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truck_tracking', '0002_remove_truck_created_at_truck_doc_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='gate',
        ),
        migrations.AddField(
            model_name='truck',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон водителя'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='doc_guid',
            field=models.CharField(max_length=128, unique=True, verbose_name='Идентификатор документа'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='status',
            field=models.CharField(choices=[('AWAITING_ARRIVAL', 'Ожидает'), ('ARRIVED', 'Приехал'), ('ON_TERRITORY', 'Заехал на территорию'), ('LOADING', 'На погрузке'), ('LOADED', 'Загружен'), ('DEPARTED', 'Выехал')], default='AWAITING_ARRIVAL', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='DrivingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate', models.CharField(max_length=10, verbose_name='Ворота')),
                ('uploading_at', models.DateTimeField(blank=True, null=True, verbose_name='Время погрузки')),
                ('store', models.CharField(blank=True, max_length=100, verbose_name='Склад')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loading_slots', to='truck_tracking.truck', verbose_name='Транспорт')),
            ],
            options={
                'verbose_name': 'Слот погрузки',
                'verbose_name_plural': 'Слоты погрузки',
            },
        ),
    ]
