# Generated by Django 5.2.2 on 2025-06-09 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck_tracking', '0003_remove_truck_gate_truck_driver_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате: +7(999)999-99-99', regex='^\\+7\\(\\d{3}\\)\\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон водителя'),
        ),
    ]
